version: "2"
services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    image: jakhrkal/snake-server
    ports:
      - "9000:9000"
  webapp:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    image: jakhrkal/snake-client
    ports:
      - "8080:80"
    depends_on: 
      - server
